@Level4BankingAPI_HostAddress = http://localhost:5021

# @name create
POST http://{{Level4BankingAPI_HostAddress}}/api/Accounts
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{auth_token}}

{
  "name": "Christina M Yuncza"
}

> {%
    client.global.set("id", response.body.id)
%}

<> 2026-01-23T142444.200.json

###
GET http://{{Level4BankingAPI_HostAddress}}/api/Accounts/{{id}}
Authorization: Bearer {{auth_token}}

<> 2026-01-23T142500.200.json
<> 2026-01-23T142459.200.json
<> 2026-01-23T142451.200.json
<> 2026-01-23T142450.200.json
<> 2026-01-23T142448.200.json
<> 2026-01-23T142447.200.json

###
POST http://{{Level4BankingAPI_HostAddress}}/api/Accounts/{{id}}/deposits
Content-Type: application/json
Accept: text/csv
Authorization: Bearer {{auth_token}}

{
  "Amount": 250
}

<> 2026-01-23T142457.200.json
<> 2026-01-23T142456.200.json

###
POST http://{{Level4BankingAPI_HostAddress}}/api/Accounts/{{id}}/withdraws
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "Amount": 200
}

###
POST http://{{Level4BankingAPI_HostAddress}}/api/Accounts/transfers
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "Amount": 1,
  "SenderId": "{{id}}",
  "ReceiverId": "{{id}}"
}

###
GET http://{{Level4BankingAPI_HostAddress}}/api/Accounts/82868a0d-a7ab-4f7d-a64a-6077ae2094ee/convert
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "CurrencyType": "EUR,CAD"
}

###
GET http://{{Level4BankingAPI_HostAddress}}/api/Accounts?sortType=balance&pageNumber=1&pageSize=20&isDescending=false
Content-Type: application/json
Accept: text/csv
Authorization: Bearer {{auth_token}}

{
  
}

###
# @name create
GET http://{{Level4BankingAPI_HostAddress}}/api/Authentication
Content-Type: application/json
Accept: text/csv

> {%
    client.global.set("auth_token", response.body.token)
%}